source "lib/import_all.sh"
source "tests/all_lib_cli_colors_tests.sh"
source "tests/all_lib_cli_styles_tests.sh"
source "tests/all_lib_cli_globals_tests.sh"
source "tests/all_lib_alert_tests.sh"
source "tests/all_lib_queries_tests.sh"
